version: "3.8"

services:
  catologdb:
    container_name: catologdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catologdb_volume:/data/db
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  discount:
    container_name: discountdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - discountdb_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123123123
      - POSTGRES_DB=discountdb
  identitydb:
    container_name: identitydb
    restart: always
    ports:
      - "1444:1433"
    volumes:
      - orderdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=admin
      - MSSQL_SA_PASSWORD=123123123
  orderdb:
    container_name: orderdb
    restart: always
    ports:
      - "1443:1433"
    volumes:
      - identitydb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=admin
      - MSSQL_SA_PASSWORD=123123123
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" 
  #catolog_api:
  #  image: catolog_api
  #  environment:
  #    - ASPNETCORE_ENVIROMENT=Development
  #    - RabbitMQ:Url=rabbitmq
  #    - DatabaseSetting:ConnectionString=mongodb://catologdb:27017
  #  ports:
  #    - "5011:80"
  #  depends_on:
  #    - catologdb
  #auth_api:
  #  container_name: auth_api
  #  environment:
  #    - ASPNETCORE_ENVIROMENT=Development
  #    - ConnectionStrings:SqlServer="Server=identitydb,1444; Database=authdb; User=sa; Password=123123123; TrustServerCertificate=True"
  #  ports:
  #    - "5010:80"
  #  depends_on:
  #    - identitydb
        